### PR TITLE
Hide edit/destroy button for moderator/user

### PR DESCRIPTION
**Pull request by komotamu**
Tested together with #39 

image

image

Not introduced by my change
image

### CODE REVIEW

**Review by xiuyu-lana — CHANGES_REQUESTED** [review]
I only see the results for cucumber. Could you also add screenshots for rspec and rubocop results?

**Review by xiuyu-lana — CHANGES_REQUESTED** [review]
image
It seems that you just hide the link to edit/destroy games from the user, but I think the user can still directly send a patch or delete request to the 'edit_game_path' or 'destroy_game_path'.  Did you test these operations? I tried to pull this branch and test it but got errors after running `git pull`

**Comment by komotamu** [comment]
> image It seems that you just hide the link to edit/destroy games from the user, but I think the user can still directly send a patch or delete request to the 'edit_game_path' or 'destroy_game_path'. Did you test these operations? I tried to pull this branch and test it but got errors after running `git pull`

image

Read the feature please.
And there is no sense to discuss about by sending the request directly. I can construct a http request to create an admin, I don't think the "cyber security" is the major concern here.

And what's your error after pulling this change?

**Comment by xiuyu-lana** [comment]
> > image It seems that you just hide the link to edit/destroy games from the user, but I think the user can still directly send a patch or delete request to the 'edit_game_path' or 'destroy_game_path'. Did you test these operations? I tried to pull this branch and test it but got errors after running `git pull`
> 
> image
> Read the feature please. And there is no sense to discuss about by sending the request directly. I can construct a http request to create an admin, I don't think the "cyber security" is the major concern here.
> 
> And what's your error after pulling this change?

I mentioned the error on Slack, in the dev channel.
As for the feature description, it was written by me. I'm sorry that I didn't provide a more detailed description. The story is not just about a front-end button. The backend also needs to be changed to include the authentication. I don't think this is just a problem with "cyber security", it's part of the story and has to be completed.

**Comment by komotamu** [comment]
> > > image It seems that you just hide the link to edit/destroy games from the user, but I think the user can still directly send a patch or delete request to the 'edit_game_path' or 'destroy_game_path'. Did you test these operations? I tried to pull this branch and test it but got errors after running `git pull`
> > 
> > 
> > image
> > Read the feature please. And there is no sense to discuss about by sending the request directly. I can construct a http request to create an admin, I don't think the "cyber security" is the major concern here.
> > And what's your error after pulling this change?
> 
> I mentioned the error on Slack, in the dev channel. As for the feature description, it was written by me. I'm sorry that I didn't provide a more detailed description. The story is not just about a front-end button. The backend also needs to be changed to include the authentication. I don't think this is just a problem with "cyber security", it's part of the story and has to be completed.

Added forbidden page for unauthorized user

**Comment by komotamu** [comment]
@xiuyu-lana please check the latest updates, I've been blocked for two days

**Comment by xiuyu-lana** [comment]
> @xiuyu-lana please check the latest updates, I've been blocked for two days

- Please provide new screenshots for rspec, cucumber, and rubocop since you have modified the code.
- Your branch has conflicts that must be resolved before merging
- The new branches, including komo/appearance, komo/auto_signout,  komo/edit_destroy, komo/log_in_out, and komo/user_management, cause errors that prevent us from pulling code from github. Would you mind renaming them to something like "komo-appearance" or "komo appearance" (instead of using slash)? 
- I didn't intend to block you. In fact, I have been blocked by the errors caused by your new branches and spending lots of time trying to resolve them.

**Comment by komotamu** [comment]
> > @xiuyu-lana please check the latest updates, I've been blocked for two days
> 
> * Please provide new screenshots for rspec, cucumber, and rubocop since you have modified the code.
> * Your branch has conflicts that must be resolved before merging
> * The new branches, including komo/appearance, komo/auto_signout,  komo/edit_destroy, komo/log_in_out, and komo/user_management, cause errors that prevent us from pulling code from github. Would you mind renaming them to something like "komo-appearance" or "komo appearance" (instead of using slash)?
> * I didn't intend to block you. In fact, I have been blocked by the errors caused by your new branches and spending lots of time trying to resolve them.

image
I do not have the same issue.

> In fact, I have been blocked by the errors caused by your new branches and spending lots of time trying to resolve them.

I don't usually develop on a Mac, so I didn't realize the case sensitivity is a problem for you. But it should not be too hard to find the solution by renaming the remote branch. 
Run `git remote prune origin` on your box and it should be gone.

**Comment by komotamu** [comment]
**won't fix those offends.
image

image

image

**Comment by xiuyu-lana** [comment]
> > > @xiuyu-lana please check the latest updates, I've been blocked for two days
> > 
> > 
> > 
> > * Please provide new screenshots for rspec, cucumber, and rubocop since you have modified the code.
> > * Your branch has conflicts that must be resolved before merging
> > * The new branches, including komo/appearance, komo/auto_signout,  komo/edit_destroy, komo/log_in_out, and komo/user_management, cause errors that prevent us from pulling code from github. Would you mind renaming them to something like "komo-appearance" or "komo appearance" (instead of using slash)?
> > * I didn't intend to block you. In fact, I have been blocked by the errors caused by your new branches and spending lots of time trying to resolve them.
> 
> image I do not have the same issue.
> > In fact, I have been blocked by the errors caused by your new branches and spending lots of time trying to resolve them.
> 
> I don't usually develop on a Mac, so I didn't realize the case sensitivity is a problem for you. But it should not be too hard to find the solution by renaming the remote branch. Run `git remote prune origin` on your box and it should be gone.

I believe it's a engineering practice not to have a new branch with the same prefix as the old branch names. E.g. `komo` and `komo/xxx`, because the branch name with `/` will generate a folder in the `.git` as a reference and thus causes issues.  I did try `git remote prune origin` but the issue is the remote branch as you said. I don't think it's appropriate for me to rename your remote branch, thus I delegate the job to you.

**Comment by komotamu** [comment]
@xiuyu-lana 

Now the issue is resolved, can you approve it?

**Comment by xiuyu-lana** [comment]
@komotamu There are 5 offenses inside the "games_controller.rb" file. However, we are only allowed to have [at most one offense per file](https://canvas.tamu.edu/courses/286611/assignments/2068910), according to the project requirement:
```
Code style: All Rubocop cops are enabled and report at most 1 style offense per file.
Assessed by: cloning the repo and running rubocop
```

 I understand you want to merge your code as soon as possible, but as a reviewer, I need to check the code quality before approving it. Thanks for your understanding.

**Comment by komotamu** [comment]
image

**Comment by komotamu** [comment]
@xiuyu-lana

**Comment by komotamu** [comment]
@xiuyu-lana 
method and class size could not be squeezed anymore, changed rubocop rules.

image

**Comment by xiuyu-lana** [comment]
@komotamu It says "1 offense autocorrectable". Please run `rubocop -A` to auto-correct the offense.
image

**Comment by komotamu** [comment]
@xiuyu-lana  auto correction result makes no sense. manually edited. 
btw, why do you need the commented-out part here?

image

**Comment by xiuyu-lana** [comment]
@komotamu Please provide proof for rspec and cucumber tests when your code is finally ready to merge. Since I don't see the latest test results, I can only pull your code and run it on my own laptop. It turns out that there are several lines inside the game controller not covered by the rspec  or cucumber tests:imageimageimageimage

Could you add more tests to improve the coverage to 100% for both cucumber and rspec? 
- Please rebase your code based on the current main branch because I have just fixed one bug regarding the coverage. 
- Please run `rm -rf coverage` to remove the previous coverage results before running rspec or cucumber. This is to make sure the resulting coverage not affected by the previous result.

**Comment by xiuyu-lana** [comment]
> @xiuyu-lana auto correction result makes no sense. manually edited. btw, why do you need the commented-out part here?
> 
> image

I think this part was added by Zach, not me. If you see my name in the history, I guess it is because I manually rebased Zach's code to solve some conflicts. The history may change in this process.

**Comment by komotamu** [comment]
@xiuyu-lana  last update


image


image

image

The only line not covered not introduced by my change. How did you get this checked in btw?
image

**Review by xiuyu-lana — APPROVED** [review]

**Pull request merged**
