### PR TITLE
allow only admin to creating games

### PR DESCRIPTION
**Pull request by komotamu**
image

image

### CODE REVIEW

**Comment by komotamu** [comment]
image

Not introduced by this change, should be introduced by #45 
image

**Comment by komotamu** [comment]
@xiuyu-lana

**Comment by nilo-tamu** [comment]
Please pull in the latest main branch to update this branch.

**Comment by komotamu** [comment]
Create API cannot be tested in cucumber because there is no way to submit a creation request on UI.

image
image


Tested in Rspec
image

rubocop
image

**Comment by xiuyu-lana** [comment]
> @xiuyu-lana Create API cannot be tested in cucumber because there is no way to submit a creation request on UI.
> 
> image 

It can be covered by cucumber actually. You had similar lines in your previous PR for destroying/editing games but uncovered by Cucumber. I added additional cucumber scenarios for them in PR45 and made everything covered.  Unfortunately, I don't have time to do it this time. Could you take a look at the previous ones and try to make cucumber cover 100% code?

**Comment by komotamu** [comment]
@xiuyu-lana alright, it's 100% now.

image
image
image

**Pull request merged**
